### ISSUE TITLE
Error in get_score_color.py:6

### ISSUE THREAD

**Issue by lhotakj** [Silleellie/pylint-github-action#1]
Hi, 
first of all, thanks for such nice action. I just installed it in my action [pylint_badge.yaml](https://github.com/lhotakj/magistro/blob/main/.github/workflows/pylint_badge.yaml) and used the basic syntax.
However my run failed, please see attached [logs](https://github.com/Silleellie/pylint-github-action/files/13854904/logs_13.zip).
Here's the detail of the error:
```
Successfully installed colorama-0.4.6 pygame-2.5.2 slack-sdk-3.26.1
Run pkgs_pth=$(python3 -c 'import re; print(" ".join(re.findall("([^\s]+)", ".")))')
  pkgs_pth=$(python3 -c 'import re; print(" ".join(re.findall("([^\s]+)", ".")))')
  pylint --exit-zero --output-format=text:pylint_score.txt,colorized $pkgs_pth
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.13/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.13/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.13/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.13/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.13/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.13/x64/lib
************* Module .
__init__.py:1:0: F0010: error while code parsing: Unable to load file __init__.py:
[Errno 2] No such file or directory: '__init__.py' (parse-error)
Run python /home/runner/work/_actions/Silleellie/pylint-github-action/v1/get_score_color.py
  python /home/runner/work/_actions/Silleellie/pylint-github-action/v1/get_score_color.py
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.13/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.13/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.13/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.13/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.13/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.13/x64/lib
Traceback (most recent call last):
  File "/home/runner/work/_actions/Silleellie/pylint-github-action/v1/get_score_color.py", line 6, in <module>
    numeric_score = re.search(r"(?<=\s)(\d+\.\d+)\/\d+(?=\s)", pylint_result).group().split("/")[0]
AttributeError: 'NoneType' object has no attribute 'group'
Error: Process completed with exit code 1.
```
Thank you for looking into it,
Jarda

**Comment by Silleellie** [comment]
Hello, thank you for opening this issue. I will look into it and update you as soon as I can :)

**Comment by Silleellie** [comment]
Hey, sorry for the late response! The issue is that the `package-path` parameter in your GA points to the root of the repository, which is not a package since there's no `__init__.py` file. So you can solve this in two ways:

- You can simply specify as `package-path` the python file to lint (which seems `main.py` in your case)
- Or you can put your `main.py` file in a package (create a new directory with the `__init__.py` file) and put the path to this newly created package as value to the `package-path` parameter

I'm realizing that maybe "package-path" is an unfortunate name for the parameter, and maybe I should change it to "lint-path" and update the documentation for your case (which is a valid one). In the meantime, please try one of the two solutions provided and let me know!

**Comment by Silleellie** [comment]
Hey, now this issue is fully solved as the new [v2](https://github.com/Silleellie/pylint-github-action/releases/tag/v2) release of this github action better documents the behaviour of linting single python files.
Feel free to reopen this issue if something's wrong!
